### ISSUE TITLE
do you know the meaning of ddos? because this isn't. and servers that use encryption or decode full LoginMessage will make this tool a jerk. 

### ISSUE THREAD

**Issue by SB-9838** [TheAcelot/brawlddos#2]

**Comment by TheAcelot** [comment]
i know, u must read 2 words in readme.md: "shitty code". It's tool created for killing servers on classic brawl core. and server can decode login message because classic brawl reader (or ByteStream) returns 0 if not bytes for read

**Comment by SB-9838** [comment]
......... would u love if someone do this for your server?

**Comment by TheAcelot** [comment]
yes, because a have antiddos :)

**Comment by BreadBSS** [comment]
lmao

**Comment by SB-9838** [comment]
for the 1k time this isn't a ddos and I bet that I can easily hacc your server.

**Comment by SB-9838** [comment]
if anti ddos was easy as you think, people wouldn't have payed for companies to give them protections

what your code is doing is checking for connection count from "1" IP that isn't a ddos

what if 3 friends play from same ip, will you ban them?
huh

**Comment by BreadBSS** [comment]
да хули ты слендился заебал уже

**Comment by TheAcelot** [comment]
> for the 1k time this isn't a ddos and I bet that I can easily hacc your server.

u read "shitty code" or no?

**Comment by TheAcelot** [comment]
> if anti ddos was easy as you think, people wouldn't have payed for companies to give them protections
> 
> what your code is doing is checking for connection count from "1" IP that isn't a ddos
> 
> what if 3 friends play from same ip, will you ban them? huh

no, because my antiddos good

**Comment by SB-9838** [comment]
nice so your anti ddos is a shitty code?

because I'm taking about it

**Comment by SB-9838** [comment]
> 

excuse me I need a minute to laugh

**Comment by TheAcelot** [comment]
> nice so your anti ddos is a shitty code?
> 
> because I'm taking about it
bruh, THIS tool is shitty code, but antiddos not.

**Comment by SB-9838** [comment]
it is :)

**Comment by TheAcelot** [comment]
no

**Comment by SB-9838** [comment]
let me guess, you're using redis server for your anti ddos?

**Comment by TheAcelot** [comment]
> let me guess, you're using redis server for your anti ddos?

no, im user only os module in python
and why u ban me at classic brawl?

**Comment by SB-9838** [comment]
you made a tool to attack servers based on cb

what do you expect from the community? to love you?

**Comment by TheAcelot** [comment]
> you made a tool to attack servers based on cb
> 
> what do you expect from the community? to love you?

a lot of dudniks using classic brawl and name it his servers. when, can't i ddos him?

**Comment by SB-9838** [comment]
no you can't
this is illegal worldwides and everyone is crediting cb
and you're not a cb developer to have the right to choose what they should do
Shockwave and PhoenixFire know what and how people are using cb since it was created

**Comment by TheAcelot** [comment]
not everyone crediting cb, a lot of users in ru community using classic brawl and name it his servers writed by him

**Comment by SB-9838** [comment]
shockwave and PhoenixFire know about this
and if someone have to take decision then should be one of them, not you.

**Comment by tailsjs** [comment]
@SB-9838 i can't decide, why anyone from"cb repo devs" cannot write simple antiddos? you can say "because not our problem". but then why did you ban a person who wrote a ddos ​​script that crashes servers based on classic brawl? why you don't give a damn about the protection of other people's servers, but you don't give a damn about the fact that some noun posted a ddos ​​script?

**Comment by SB-9838** [comment]
what he did is attacking the community which obviously won't return love from them
and for anti ddos, cb is made as a server base
+
he should stop saying that he did anti ddos, I bet that what he did is anti spam connections from 1 ip and would ban ip if multiple people are playing on it
how can you know if 20 real clients are connecting at same time from different ips or that they are a code connecting by different ips?
would you ban these 20 players?

**Comment by tailsjs** [comment]
i gonna amaze you "HE DON'T CARE THE COMMUNITY". he can ddos any server, he can post any shit, that gonna hurt cb community servers. he don't care.
even if cb is server base, why anyone from "cb repo devs", that LOVES COMMUNITY AND GONNA SUPPORT THEY don't gives a shit about ddos security? ("cb is made as a server base" not an argument.)

he really did antiddos. he showed me. 

"20 real clients are connecting at same time but different ip" if your antiddos is shit, it gonna ban all 20 players.

**Comment by SB-9838** [comment]
1-you can't know which one is real client from these 20
all different ips
all carry same data
2-about community, what I meant is, if he do something for them = he's not welcomed
and that's why he was banned

**Comment by tailsjs** [comment]
1. why is it? i have simple antiddos, that i writed on knee. it bans fakeclients perfectly

2. "if he do something for them = he's not welcomed". wow, looks like i cannot post some exclusive things from ida pro to github, i gonna be not welcomed. sooo sad :(
also you're too not welcomed because cpp-brawl

**Comment by SB-9838** [comment]
nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data
wonderful.

**Comment by TheAcelot** [comment]
> 1. why is it? i have simple antiddos, that i writed on knee. it bans fakeclients perfectly
> 2. "if he do something for them = he's not welcomed". wow, looks like i cannot post some exclusive things from ida pro to github, i gonna be not welcomed. sooo sad :(
>    also you're too not welcomed because cpp-brawl

he named my bytestream bad but 
he's good bytestream
void ByteStream::writeInt(int a1)
{
	if (canWrite(4))
	{
		buffer[offset] = (a1 >> 24 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 >> 16 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 >> 8 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 & 0xFF);
		offset += 1;
	}
and my bad bytestream
	void ByteStream::writeInt(int i)
{
	buffer.push_back(i>>24);
	buffer.push_back(i>>16);
	buffer.push_back(i>>8);
	buffer.push_back(i);
}
catch the difference?

**Comment by TheAcelot** [comment]
> nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.

very easy to verify client

**Comment by SB-9838** [comment]
catch the difference in writeVInt
also vector and chars are different obviously, lol

**Comment by SB-9838** [comment]
> > nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.
> 
> very easy to verify client

yeye
it's like choosing a cup of water between 20 cups that are 100% identical

**Comment by TheAcelot** [comment]
> catch the difference in writeVInt also vector and chars are different obviously, lol

but vector better then char in bytestream :)

**Comment by TheAcelot** [comment]
> > > nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.
> > 
> > 
> > very easy to verify client
> 
> yeye it's like choosing a cup of water between 20 cups that are 100% identical

my antiddos can verify client, you may not believe it but still

**Comment by tailsjs** [comment]
> nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.

yes.

**Comment by tailsjs** [comment]
> > > > nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.
> > > 
> > > 
> > > very easy to verify client
> > 
> > 
> > yeye it's like choosing a cup of water between 20 cups that are 100% identical
> 
> my antiddos can verify client, you may not believe it but still

true

**Comment by SB-9838** [comment]
> > catch the difference in writeVInt also vector and chars are different obviously, lol
> 
> but vector better then char in bytestream :)

huh?
who said?

**Comment by SB-9838** [comment]
> > nice you wanna convince me that you can know fake client between 20 clients that have different locations, ip isn't a host, and they carry same data wonderful.
> 
> yes.

whatever, talking with him is like talking with a wall, you won't reach a result.

**Comment by TheAcelot** [comment]
> > > catch the difference in writeVInt also vector and chars are different obviously, lol
> > 
> > 
> > but vector better then char in bytestream :)
> 
> huh? who said?

im, compare buffer.erase(buffer.begin(),buffer.begin()+2); and result = ((buffer[offset]) << 24 | (buffer[offset + 1]) << 16 | (buffer[offset + 2]) << 8 | (buffer[offset + 3]));  offset += 4; you can read bytes without offset var!!! 
and buffer[offset] = (a1 >> 24 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 >> 16 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 >> 8 & 0xFF);
		offset += 1;
		buffer[offset] = (a1 & 0xFF);
		offset += 1; with 
	buffer.push_back(i>>24);
	buffer.push_back(i>>16);
	buffer.push_back(i>>8);
	buffer.push_back(i);
u can write bytes without offset

**Comment by tailsjs** [comment]
@TheAcelot 
TRYING TO CAPTURE "cb repo devs" IN HYPOMERISY
@@@
ASKING WHY IT IS IMPOSSIBLE TO MAKE AT LEAST THE SIMPLE ANTIDDOS
@@@
"YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL"
@@@
WELL THEN IF YOU LOVE YOUR COMMUNITY, WHY DO YOU GIVE THEM A SERVER THAT YOU CAN CRASH EASILY? A MAN SPECIALLY POSTED A DDOS SCRIPT TO SHOW YOUR ATTITUDE TO THE COMMUNITY BUT YOU BANNED HIM
@@@
"YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL"

**Comment by SB-9838** [comment]
> > > > catch the difference in writeVInt also vector and chars are different obviously, lol
> > > 
> > > 
> > > but vector better then char in bytestream :)
> > 
> > 
> > huh? who said?
> 
> im, compare buffer.erase(buffer.begin(),buffer.begin()+2); and result = ((buffer[offset]) << 24 | (buffer[offset + 1]) << 16 | (buffer[offset + 2]) << 8 | (buffer[offset + 3])); offset += 4; you can read bytes without offset var!!! and buffer[offset] = (a1 >> 24 & 0xFF); offset += 1; buffer[offset] = (a1 >> 16 & 0xFF); offset += 1; buffer[offset] = (a1 >> 8 & 0xFF); offset += 1; buffer[offset] = (a1 & 0xFF); offset += 1; with buffer.push_back(i>>24); buffer.push_back(i>>16); buffer.push_back(i>>8); buffer.push_back(i); u can write bytes without offset

same result so?
you didn't make any differ

**Comment by TheAcelot** [comment]
> > > > > catch the difference in writeVInt also vector and chars are different obviously, lol
> > > > 
> > > > 
> > > > but vector better then char in bytestream :)
> > > 
> > > 
> > > huh? who said?
> > 
> > 
> > im, compare buffer.erase(buffer.begin(),buffer.begin()+2); and result = ((buffer[offset]) << 24 | (buffer[offset + 1]) << 16 | (buffer[offset + 2]) << 8 | (buffer[offset + 3])); offset += 4; you can read bytes without offset var!!! and buffer[offset] = (a1 >> 24 & 0xFF); offset += 1; buffer[offset] = (a1 >> 16 & 0xFF); offset += 1; buffer[offset] = (a1 >> 8 & 0xFF); offset += 1; buffer[offset] = (a1 & 0xFF); offset += 1; with buffer.push_back(i>>24); buffer.push_back(i>>16); buffer.push_back(i>>8); buffer.push_back(i); u can write bytes without offset
> 
> same result so? you didn't make any differ

but it's takes less strings with code and it's more convenient and easy

**Comment by tailsjs** [comment]
> @TheAcelot TRYING TO CAPTURE "cb repo devs" IN HYPOCRISY @@@ ASKING WHY IT IS IMPOSSIBLE TO MAKE AT LEAST THE SIMPLE ANTIDDOS @@@ "YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL" @@@ WELL THEN IF YOU LOVE YOUR COMMUNITY, WHY DO YOU GIVE THEM A SERVER BASE THAT CAN CRASH EASILY? A DUDE SPECIALLY POSTED A DDOS SCRIPT TO SHOW YOUR ATTITUDE TO THE COMMUNITY BUT YOU BANNED HIM @@@ "YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL"

AND ALSO, "HOW DO YOU DIFFERENTIFY 20 CLIENTS THAT CONNECT AT A TIME? FAKE OR NOT"
@@@
ARE YOU STUPID OR SOMETHING? WHO TOLD YOU TO CHECK THE CLIENT BY IP? YOU HAVE A CLIENT THAT SENDS A PACKETS. IT'S ENOUGH

**Comment by SB-9838** [comment]
> > @TheAcelot TRYING TO CAPTURE "cb repo devs" IN HYPOCRISY @@@ ASKING WHY IT IS IMPOSSIBLE TO MAKE AT LEAST THE SIMPLE ANTIDDOS @@@ "YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL" @@@ WELL THEN IF YOU LOVE YOUR COMMUNITY, WHY DO YOU GIVE THEM A SERVER BASE THAT CAN CRASH EASILY? A DUDE SPECIALLY POSTED A DDOS SCRIPT TO SHOW YOUR ATTITUDE TO THE COMMUNITY BUT YOU BANNED HIM @@@ "YOU KNOW CLASSIC BRAWL IS SERVER BASE AND WE LOVE OUR COMMUNITY IN GENERAL"
> 
> AND ALSO, "HOW DO YOU DIFFERENTIFY 20 CLIENTS THAT CONNECT AT A TIME? FAKE OR NOT" @@@ ARE YOU STUPID OR SOMETHING? WHO TOLD YOU TO CHECK THE CLIENT BY IP? YOU HAVE A CLIENT THAT SENDS A PACKETS. IT'S ENOUGH

nice
they're sending same packet with same data
now explain what you would do

**Comment by terexdev** [comment]
срачи 228 на гитхабе:

**Comment by BreadBSS** [comment]
сочный sraitstrim.cpp brawl

**Comment by terexdev** [comment]
ку брид

**Comment by xeondev1337** [comment]
> > catch the difference in writeVInt also vector and chars are different obviously, lol
> 
> but vector better then char in bytestream :)

dynamic arrays better than vector for that purpose.

**Comment by terexdev** [comment]
JEJ
